theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - toc.integrate
    - toc.collapse
    - navigation.expand
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.tabs.sticky
  palette:
    - scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Light mode

site_name: Puma
site_description: Documentação técncica do projeto Puma
site_author: Mateus Vieira & Lucas Antunes
repo_url: https://github.com/PUMA-projeto/docs
repo_name: GitHub

plugins:
  - search:
      lang: en
      separator: '[\s\-]+'

extra:
  analytics:
    provider: google
    property: UA-XXXXX-Y
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PUMA-projeto/docs

strict: true
use_directory_urls: true
nav:
  - Home: index.md
  - Projeto:
    - Overview: project/overview.md
    - Ferramentas: project/tools.md
  - Produto:
    - MVP: product/mvp.md
    - Backlog: product/backlog.md
  - Setup & Configuration:
      - MkDocs:
          - MkDocs Configuration: setup/mkdocs-configuration.md
          - MkDocs Setup: setup/mkdocs-setup.md
      - Environment Setup:
          - Python Virtual Environment: setup/python-venv-setup.md
          - Publishing Guide: setup/publishing-guide.md
      - README: setup/readme.md
  - References: references.md
